# GitHub Workflow to update pdm backend dependencies using Dependabot
name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update dependencies
        uses: pdm-project/update-deps-action@main