name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'requirements.txt'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set ISO Date
      id: set-date
      run: |
        echo "DATE_TAG=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV

    - name: Pull existing latest image (if exists)
      id: pull-latest
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest || echo "No previous latest tag found"

    - name: Backup existing latest as rollback tag (if exists)
      run: |
        if docker inspect ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest > /dev/null 2>&1; then
          docker tag ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest-${{ env.DATE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest-${{ env.DATE_TAG }}
        fi

    - name: Build and push new latest image
      id: push-latest
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest

  rollback:
    name: Rollback to Previous Latest
    runs-on: ubuntu-latest
    needs: build-and-push
    if: failure()  # Only runs if the build-and-push job fails
    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Rollback to previous latest image
      run: |
        echo "Build or push failed. Rolling back to previous latest image..."
        docker pull ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest-${{ env.DATE_TAG }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/realrate-private:${{ env.DATE_TAG }} ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/realrate-private:latest
