name: build_on_docker_image
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aadesh/test-workflows:latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python 3.7
        run: python --version
      - name: Backend code tests
        run: |
          # Stop the build if there are any Python syntax errors or undefined names
          flake8 main.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The github-editor is 127 character long.
          flake8 main.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pytest --cov=./ --cov-report=xml
